### ISSUE TITLE
TRG 2.04 leading product repository

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal#131]
The leading repository should not be pre- or suffixed. Expected name for your leading repositoriy is _portal_.

Solves #116

**Comment by evegufy** [comment]
As TRG 2.04 was written in that manner long after our repository structure was already in place and renaming a repository doesn't just come down to the mere act of [renaming](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository), we'll need to analyse the tasks connected to it, and then decide if the effort fits the benefit. We'll do that for one of the next releases.
Please annotate that accordingly in https://github.com/eclipse-tractusx/portal-cd/issues/126 and close one the issues yours or https://github.com/eclipse-tractusx/portal-cd/issues/116.

**Comment by carslen** [comment]
Will be implemented in future, closing #116 and leave this one open for tracking.

**Comment by FaGru3n** [comment]
solved by https://github.com/eclipse-tractusx/.eclipsefdn/pull/60

**Comment by evegufy** [comment]
> No update for 24.03 release, revisited for 24.05

need to revert the statement, it's implemented now, so in time for the 24.03 release
