### ISSUE TITLE
QG X checks (Release 24.03) 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#203]
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner: @jjeroch 
Dev SPOC: @evegufy 

Portal:
- Portal Chart Version: [portal-1.8.0(-RC8)](https://github.com/eclipse-tractusx/portal-cd/releases/tag/portal-1.8.0-RC8)
  - [QG Checklist Leading Repo](https://github.com/eclipse-tractusx/portal-cd/issues/203)
- Portal Frontend: [v1.8.0(-RC6)](https://github.com/eclipse-tractusx/portal-frontend/releases/tag/v1.8.0-RC6)
  - [QG Checklist Frontend](https://github.com/eclipse-tractusx/portal-frontend/issues/560)
- Portal Backend: [v1.8.0(-RC7)](https://github.com/eclipse-tractusx/portal-backend/releases/tag/v1.8.0-RC7)
  - [QG Checklist Backend](https://github.com/eclipse-tractusx/portal-backend/issues/539)
- Portal Assets: [v1.8.0(-RC5)](https://github.com/eclipse-tractusx/portal-assets/releases/tag/v1.8.0-RC5)
  - [QG Checklist Portal Assets](https://github.com/eclipse-tractusx/portal-assets/issues/270)
- Portal Frontend Registration: [v1.6.0(-RC5)](https://github.com/eclipse-tractusx/portal-frontend-registration/releases/tag/v1.6.0-RC5)
  - [QG Checklist Portal Frontend Registration](https://github.com/eclipse-tractusx/portal-frontend-registration/issues/127)

IAM:
- CentralIdP Chart Version: [2.1.0(-RC1)](https://github.com/eclipse-tractusx/portal-iam/releases/tag/centralidp-2.1.0-RC1)
- SharedIdP Chart Version: [2.1.0(-RC1)](https://github.com/eclipse-tractusx/portal-iam/releases/tag/sharedidp-2.1.0-RC1)
  - [QG-Checklist](https://github.com/eclipse-tractusx/portal-iam/issues/51)

Release Management Reference Issue: https://github.com/eclipse-tractusx/sig-release/issues/499

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4) editable static files

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
https://github.com/eclipse-tractusx/portal-assets/issues/210 --> implemented since 23.12
https://github.com/eclipse-tractusx/portal-cd/issues/131 --> implemented since 23.12
https://github.com/eclipse-tractusx/portal/issues/205
- [x] #208
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
--> implemented since 23.12
https://github.com/eclipse-tractusx/portal-assets/issues/206
https://github.com/eclipse-tractusx/portal-frontend/issues/381
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/83
https://github.com/eclipse-tractusx/portal-backend/issues/358
https://github.com/eclipse-tractusx/portal-iam/issues/36
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03) image has `USER` command and Non Root Container
- [x] [TRG 4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) released image must be placed in `DockerHub`, remove `GHCR` references 
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) separate notice file for `DockerHub` has all necessary information

#### TRG 5 Helm

- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart requirements
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [ ] #207
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] #206
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

**Comment by FaGru3n** [comment]
Hi @evegufy, TRG Check for leading repo done. 

Please recheck the findings and we will update the issue. 

Thanks in advance.

**Comment by SebastianBezold** [comment]
Closing the QG issue, with the default CPU and memory requests for the Chart missing.

**Comment by evegufy** [comment]
Clarification: CPU and memory requests are set. CPU and memory requests limits are configured but commented out in the [values.yaml](https://github.com/eclipse-tractusx/portal/blob/portal-1.8.0-RC8/charts/portal/values.yaml#L114) but can be set at all times when using the chart. Setting the limits in the values.yaml will be addressed in the next release.
