### ISSUE TITLE
TRG 2.04 leading product repository

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal#208]
Would be very nice to have more detailed information what this chart deliveres and also maybe referencing in the documentation to each component

**Comment by SebastianBezold** [comment]
I think the improvements made in [2eb0d84345cba59095b2bba5e91153ce44c51574](https://github.com/eclipse-tractusx/portal/commit/2eb0d84345cba59095b2bba5e91153ce44c51574) are fine
