### ISSUE TITLE
Move out of catenax-ng GH org

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#342]
We need to to move out of the catenax-ng GH org:
 
Schedule:
14.06.2024 (EOB): Catena-X ng set to READ-ONLY
26.07.2024 (EOB): Catena-X ng will be DELETED

The READ-ONLY deadline doesn't apply to our team as a roadmap with the PCWM team to move out until the deletion deadline was defined.

**Forks**

https://github.com/catenax-ng/tx-portal-backend
https://github.com/catenax-ng/tx-portal-shared-components
https://github.com/catenax-ng/tx-portal-cd
https://github.com/catenax-ng/tx-portal-assets
https://github.com/catenax-ng/tx-portal-frontend
https://github.com/catenax-ng/tx-portal-frontend-registration
https://github.com/catenax-ng/tx-policy-hub
https://github.com/catenax-ng/tx-ssi-credential-issuer
https://github.com/catenax-ng/tx-ssi-authority-schema-registry

_One option_ would be to replicate our current fork setup, which are mainly relevant for the contributors in our teams, in the CX Association GH Org, which would mean coordination work with the association at the same time it's also not the preferred solution by the them as is means administration efforts. 

_Other option_:
The question is also if we really need to replicate the current fork setup somewhere else of if it'd be an option that contributors in our team are working in personal forks, as normal contributors do. 

**Helper repositories**

Regardless of the forks, we still need to find a solution for our helper repos:
https://github.com/catenax-ng/product-portal-tools
https://github.com/catenax-ng/product-portal-swagger

if we switch to personal forks, we should check if the [documentation](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md) may should be enhanced and we should move the CI sonarcloud scan for the portal-backend to Tractus-X.

**Comment by evegufy** [comment]
Regarding [product-portal-swagger](https://github.com/catenax-ng/product-portal-swagger) isn't needed anymore according to @oyo .

Regarding forks: "Dev flow: change from forks in catenax-ng to own forks" introduction meeting with team was held on July 11, 2024. 
In essence, we’ll follow the usual way how to contribute after the catenax-ng are gone:
https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md

Regarding [product-portal-tools](https://github.com/catenax-ng/product-portal-tools):
pgadmin4 has been move to https://github.com/catenax-eV/infrastructure-tools
tdb: reportportal and jira tranfer scipt

**Comment by Phil91** [comment]
regarding the jira transfer script, there is a repo which can be found here: https://github.com/Phil91/jihub which is publicly available. in my opinion we can remove it / don't have to move it somewhere else

@evegufy fyi

**Comment by evegufy** [comment]
reportportal has been forked into personal fork for now https://github.com/evegufy/product-portal-tools
