### ISSUE TITLE
Release 2.1.0 Release Candidate to INT

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal#350]
### Ticket Details

**Description:**
- Build and deploy the Release 2.1.0 release candidate to the INT environment.
- Perform necessary smoke testing to validate the deployment.
- If all tests pass, promote the release candidate to the PROD environment.

**Tasks:**
1. Checkout the 2.1.0-RC branch from the codebase.
2. Build the release candidate artifacts.
3. Deploy the release candidate to the INT environment.
4. Run smoke tests to validate the deployment.
5. Communicate the release to the relevant stakeholders.

**Definition of Done:**
- Release 2.1.0 RC deployed to INT environment.
- Smoke tests executed and passed.
- Release candidate promoted to PROD environment.
- Release notes and documentation updated.
- Stakeholders informed about the release.

**Acceptance Criteria:**
- Release 2.1.0 RC deployed successfully to INT.
- Smoke tests executed without any failures.
- Stakeholders notified about the new release.

**Pre-Requisite:**
- Julia to run tests on dev and approve to create the RC
- ChangeLog created

**Comment by evegufy** [comment]
Hi @jjeroch you mention "PROD environment" - which we don't have - in this issue, did you use some issue template, copy/paste error?

**Comment by evegufy** [comment]
Also released the SAP DIM Middle Layer v1.2.0 as the repo and packages are public now and performed blue green deployment from https://github.com/Phil91/dim-client/releases/tag/dim-0.0.7 to https://github.com/SAP/ssi-dim-middle-layer/releases/tag/dim-1.2.0
