### ISSUE TITLE
NGINX Issue on release test branch env.

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal#352]
On rc.dev with deployment 2.1.0 RC1 marketplace/apps backend APIs as well as service APIs run on 502 NGINX error

<img width="336" alt="image" src="https://github.com/eclipse-tractusx/portal/assets/94133633/765a71a0-a306-440d-8d51-614483cfa5b6">

Impact: test impossible

**Comment by evegufy** [comment]
Hi @jjeroch I guess your testing with the wrong path, the correct one for the app marketplace is (and always was) `api/apps` and for service `/api/services`.
If that's not clarifying the issue: please provide more information, as I can't reproduce the error.

**Comment by jjeroch** [comment]
@evegufy successfully running now. Not sure why it didnt before

**Comment by evegufy** [comment]
@jjeroch I saw the issue today as well and its because the service is a bit short on memory, fix https://github.com/eclipse-tractusx/portal/pull/359
