### ISSUE TITLE
Legal Names | Length Changes and Special Characters | Portal Registration Frontend | Portal Backend

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal#360]
### Description
We have some limitations to company REGEX that prevents onboarding of some customers.

#### 1. Special Language Characters (Pending decision)
Currently the REGEX for legal company names is very restrictive. Special characters for some languages like German or French is allowed (e.g. üäöáè).
Other languages are not considered:
- Polish: ĄĆĘŁŃÓŚŹŻ
- Chinese: 你好 世界

Options:
1. Keep as is: only A-Z a-z À-ÿ
2. Allow characters for languages that are on white/yellow list
3. Allow characters for all languages

##### Additional Information
For 1. companies need translated legal name to onboard their company.
Options 2. & 3. have some additional technical risks since some components (bpdm/clearing house) might not support special characters of this type.

#### 2. Company Name Length (Required change for us)
There are companies with very long company names. We could find suppliers/partners in BPDM pool with up to 160 characters (more can happen but is unrealistic).
Now: 2-50 characters (currently counting white spaces)
Expected: 1-160

##### Additional Information
UI risk:
- Very long legal name needs to work with input fields
- Needs to work in company data

Compatibility risk ???

### Acceptance Criteria

- [ ] 1. Decision on special language characters is made
- [ ] 2. If required by 1.: New REGEX allows for special language characters (Portal Registration Frontend & Portal Backend)
- [ ] 3.1 New length for company names is applied to REGEX (Portal Registration Frontend & Portal Backend)
- [ ] 3.2 UI works as intended

### Additional Information
I have code ready for both changes with test cases. Waiting for decision on special character topic before creating PRs.

@jjeroch @evegufy 

Usage of UNICODE scripts for extended REGEX like /p{L} requires minimum compile target of EC6
cc: @oyo

**Comment by nicoprow** [comment]
BPDM Compatibility:

BPDM allows up to 250 characters for company names and is unicode compatible. Characters for Polish or Chinese for example are therefore also allowed.

I don't see any issue with this change regarding BPDM compatibility.

**Comment by typecastcloud** [comment]
@MaximilianHauer 
Hi Max, we still have chinese/thai/polish characters open as a topic.

There is a way to simplify REGEX via unicode scripts. \p{Letter} covers all letters in any language for example. See [unicode scripts](https://www.regular-expressions.info/unicode.html).

This would require our frontends to compile at least ES6 since support from then on. (compilerOptions still targets es5)

CC: @ybidois
