### ISSUE TITLE
App Approve | App Manager is not receiving the notification

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal#370]
### Current Behavior
App Manager is not receiving the notification on an App Approval by an authorised approver but Service Manager is receiving it instead.

### Expected Behavior
App Manager should received Approval of App notification instead of Service Manager.

### Steps To Reproduce

1. Log in to portal as CX-Operator.
2. Navigate to the "App Release Process" page and Release an App (currently App Manager is not able to do so, because there is an issue, please follow the [issue](https://github.com/eclipse-tractusx/portal-backend/issues/826) for more details)
3. Navigate to the "App Management: Admin Board" page.
4. Locate an application in "In Review" status.
5. Click on the approval icon to approve the application.
6. Verify if a notification is received on the portal interface (Notification) or via email.

### Findings
This issue is related to the notification of an APP. App Manager is not receiving the notification if Admin approves the APP but when I investigate it so, I found that `Service Manager` is receiving the APP's notification instead

On further investigation, I found that wrong role `Service Manager` has been mentioned instead of `App Manager` under `approveAppUserRoles` param in CD repo:

```
appmarketplace.approveAppUserRoles.role0 : `"Sales Manager"`
appmarketplace.approveAppUserRoles.role1 : `"Service Manager"`

```
https://github.com/Cofinity-X/portal-charts/blob/262d6c60e56d88f5ecaea1291be3a0218e2ad215/portal/charts/values.yaml#L504

**Comment by typecastcloud** [comment]
For decline the receiving user is coming from ServiceManagerRoles:
https://github.com/eclipse-tractusx/portal-backend/blob/e20a452aa7aa51b7ed43175debbebb4f9808219c/src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs#L366

Either we need AppManagerRoles or DeclineAppUserRoles config.
