### ISSUE TITLE
English language is not reflecting for wallet page

### ISSUE THREAD

**Issue by anjuchaurasiya** [eclipse-tractusx/portal#389]
### Current Behavior

The error msg showed in DE instead of EN

### Expected Behavior

The error msg should be in selected language

### Steps To Reproduce

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/fc5ba291-5efc-4f8a-aa22-cf890b36364d">

**Comment by evegufy** [comment]
Hi @anjuchaurasiya as far as I see on the screenshot everything is in English, for instance "Unknown", "Not Connecet". Could you please highlight more where English Language is not reflected?

**Comment by anjuchaurasiya** [comment]
Hi @evegufy ,
Thank you for looking into this. The msg below "My Company Wallet" seems in a diff language. That was my concern.

**Comment by evegufy** [comment]
Hi @anjuchaurasiya as Lorem Ipsum isn't a different language, see https://en.wikipedia.org/wiki/Lorem_ipsum, I'll go ahead  with closing the issue, thank you for being so attentive!
