### ISSUE TITLE
Remove custodian wallet address 

### ISSUE THREAD

**Issue by gitbooma** [eclipse-tractusx/portal#394]
Update helm chart references by removing unused config: custodian wallet address

@jjeroch confirmed that this is old code and needs to be cleaned up.

Analysis is needed by Backend & DevOps and then it can be removed.

Impacted files:

https://github.com/eclipse-tractusx/portal/blob/e03941fa7ffccdb9ac9845338dddb168dec0ec9f/charts/portal/values.yaml#L57

https://github.com/eclipse-tractusx/portal/blob/e03941fa7ffccdb9ac9845338dddb168dec0ec9f/charts/portal/templates/cronjob-backend-processes.yaml#L167-L168

https://github.com/eclipse-tractusx/portal/blob/e03941fa7ffccdb9ac9845338dddb168dec0ec9f/charts/portal/templates/deployment-backend-administration.yaml#L137-L138

https://github.com/eclipse-tractusx/portal/blob/e03941fa7ffccdb9ac9845338dddb168dec0ec9f/charts/portal/templates/deployment-frontend-portal.yaml#L69-L70

I can work on the DevOps changes part. 

cc: @evegufy

**Comment by evegufy** [comment]
Hi @gitbooma great that you think about removing obsolete configuration. Just from what you write it would mean removing the config for the managed identity wallet (or at least partially removing it, as there's more config which wouldn't make sense without the address anymore), and I'm not aware that this one is obsolete - yes, not relevant at the moment but it's assumed and hoped that it becomes relevant again.

I'll also try to clarify with @jjeroch, this might be a misunderstanding.

**Comment by jjeroch** [comment]
@gitbooma misunderstanding. SD Factory the url must get removed; for Portal it stays.

**Comment by gitbooma** [comment]
Thanks @jjeroch  @evegufy , closing the ticket as there is nothing pending.
