### ISSUE TITLE
DIM Wrapper adjustments

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal#395]
This issue serves as placeholder to make the work of the dim middle layer visible in the portal project.

The following issues are currently worked on:

- [x] https://github.com/SAP/ssi-dim-middle-layer/issues/67
- [x] https://github.com/SAP/ssi-dim-middle-layer/issues/66
- [x] https://github.com/SAP/ssi-dim-middle-layer/issues/63
- [x] https://github.com/SAP/ssi-dim-middle-layer/issues/60
- [x] https://github.com/SAP/ssi-dim-middle-layer/issues/56

**Comment by MaximilianHauer** [comment]
closing this as implicitly tested
