### ISSUE TITLE
Invite OSP email | sig#779 - Inconsistent page names | missed changes | v2.2.0

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal#439]
### Info
Hi @evegufy @oyo @manojava-gk @MaximilianHauer 

Some of the pages got renamed in eclipse-tractusx/portal-frontend#696. Default helm values should be aligned.

Example:
`externalRegistrationPath: "/consent_osp"` ->
`externalRegistrationPath: "/consentOsp"
`
- [x] Check default value for "path:" variables
- [x] Default path are adjusted

### Current Behavior
When inviting a company via OSP, the invited user is linked to /consent_osp in email and gets an error.

### Expected Behavior
Email links to correct path /consentOsp.

### Steps To Reproduce

1. Invite via OSP
2. Click on link in email
3. Check url + error after login

**Comment by evegufy** [comment]
Hi @manojava-gk could you please look into this, it's just changing one value https://github.com/eclipse-tractusx/portal/blob/4a80153abede5b6965f760418857e404942b5e03/charts/portal/values.yaml#L899

**Comment by typecastcloud** [comment]
> Hi @manojava-gk could you please look into this, it's just changing one value
> 
> https://github.com/eclipse-tractusx/portal/blob/4a80153abede5b6965f760418857e404942b5e03/charts/portal/values.yaml#L899

Can you guys also check other "Path:" values? I think others are just **not** case sensitive and don't cause issues. Thanks!
