### ISSUE TITLE
"How to contribute" links broken after TRG 1 alignment

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal#483]
### Current Behavior

After the merge of https://github.com/eclipse-tractusx/portal-assets/pull/428 the "How to contribute" links are broken.

See examples from portal repo:

- CONTRIBUTING.md
https://github.com/eclipse-tractusx/portal/blob/main/CONTRIBUTING.md#how-to-contribute

- .github/pull_request_template.md
https://github.com/eclipse-tractusx/portal-frontend/blob/main/.github/pull_request_template.md?plain=1#L17

Please check in the main branch of all the following repos if those links still work:

https://github.com/eclipse-tractusx/portal
https://github.com/eclipse-tractusx/portal-frontend
https://github.com/eclipse-tractusx/portal-frontend-registration
https://github.com/eclipse-tractusx/portal-shared-components
https://github.com/eclipse-tractusx/portal-backend
https://github.com/eclipse-tractusx/portal-assets
https://github.com/eclipse-tractusx/portal-iam
https://github.com/eclipse-tractusx/policy-hub
https://github.com/eclipse-tractusx/ssi-credential-issuer
https://github.com/eclipse-tractusx/ssi-authority-schema-registry

And raise a PR to fix it if not.

### Expected Behavior

"How to contribute" links work

**Comment by CDiezRodriguez** [comment]
https://github.com/eclipse-tractusx/portal-iam is okay
